<?php

namespace Container8I003xq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlayerInvitationControllerremoveInvitationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.C_WqeYK.App\Controller\PlayerInvitationController::removeInvitation()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.C_WqeYK.App\\Controller\\PlayerInvitationController::removeInvitation()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'invitationRepository' => ['privates', 'App\\Repository\\InvitationRepository', 'getInvitationRepositoryService', false],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'invitationRepository' => 'App\\Repository\\InvitationRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\PlayerInvitationController::removeInvitation()', $container);
    }
}
