<?php

namespace ContainerXkoRc0e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Za4wbqNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Za4wbqN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Za4wbqN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\GroupeJDRController::index' => ['privates', '.service_locator.uqAk9vV.App\\Controller\\GroupeJDRController::index()', 'getGroupeJDRControllerindexService', true],
            'App\\Controller\\GroupeJDRController::new' => ['privates', '.service_locator..fUBbna.App\\Controller\\GroupeJDRController::new()', 'getGroupeJDRControllernewService', true],
            'App\\Controller\\GroupeJDRController::show' => ['privates', '.service_locator.b7WMJCv.App\\Controller\\GroupeJDRController::show()', 'getGroupeJDRControllershowService', true],
            'App\\Controller\\GroupeJDRController::edit' => ['privates', '.service_locator.CzRsto_.App\\Controller\\GroupeJDRController::edit()', 'getGroupeJDRControllereditService', true],
            'App\\Controller\\GroupeJDRController::delete' => ['privates', '.service_locator.8bi2G4e.App\\Controller\\GroupeJDRController::delete()', 'getGroupeJDRControllerdeleteService', true],
            'App\\Controller\\InvitationController::index' => ['privates', '.service_locator.BhavcCd.App\\Controller\\InvitationController::index()', 'getInvitationControllerindexService', true],
            'App\\Controller\\InvitationController::respond' => ['privates', '.service_locator.t03gBDU.App\\Controller\\InvitationController::respond()', 'getInvitationControllerrespondService', true],
            'App\\Controller\\MyGameController::index' => ['privates', '.service_locator.RvFgQI_.App\\Controller\\MyGameController::index()', 'getMyGameControllerindexService', true],
            'App\\Controller\\PlayerInvitationController::checkUser' => ['privates', '.service_locator.D_ODzvE.App\\Controller\\PlayerInvitationController::checkUser()', 'getPlayerInvitationControllercheckUserService', true],
            'App\\Controller\\PlayerInvitationController::invitePlayer' => ['privates', '.service_locator.BVux.Zu.App\\Controller\\PlayerInvitationController::invitePlayer()', 'getPlayerInvitationControllerinvitePlayerService', true],
            'App\\Controller\\PlayerInvitationController::removeUserFromJdr' => ['privates', '.service_locator.cPirmC2.App\\Controller\\PlayerInvitationController::removeUserFromJdr()', 'getPlayerInvitationControllerremoveUserFromJdrService', true],
            'App\\Controller\\ProfileController::edit' => ['privates', '.service_locator.gigYcBf.App\\Controller\\ProfileController::edit()', 'getProfileControllereditService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.QVAk1vM.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController::verifyUserEmail' => ['privates', '.service_locator.fdTWzgN.App\\Controller\\RegistrationController::verifyUserEmail()', 'getRegistrationControllerverifyUserEmailService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\GroupeJDRController:index' => ['privates', '.service_locator.uqAk9vV.App\\Controller\\GroupeJDRController::index()', 'getGroupeJDRControllerindexService', true],
            'App\\Controller\\GroupeJDRController:new' => ['privates', '.service_locator..fUBbna.App\\Controller\\GroupeJDRController::new()', 'getGroupeJDRControllernewService', true],
            'App\\Controller\\GroupeJDRController:show' => ['privates', '.service_locator.b7WMJCv.App\\Controller\\GroupeJDRController::show()', 'getGroupeJDRControllershowService', true],
            'App\\Controller\\GroupeJDRController:edit' => ['privates', '.service_locator.CzRsto_.App\\Controller\\GroupeJDRController::edit()', 'getGroupeJDRControllereditService', true],
            'App\\Controller\\GroupeJDRController:delete' => ['privates', '.service_locator.8bi2G4e.App\\Controller\\GroupeJDRController::delete()', 'getGroupeJDRControllerdeleteService', true],
            'App\\Controller\\InvitationController:index' => ['privates', '.service_locator.BhavcCd.App\\Controller\\InvitationController::index()', 'getInvitationControllerindexService', true],
            'App\\Controller\\InvitationController:respond' => ['privates', '.service_locator.t03gBDU.App\\Controller\\InvitationController::respond()', 'getInvitationControllerrespondService', true],
            'App\\Controller\\MyGameController:index' => ['privates', '.service_locator.RvFgQI_.App\\Controller\\MyGameController::index()', 'getMyGameControllerindexService', true],
            'App\\Controller\\PlayerInvitationController:checkUser' => ['privates', '.service_locator.D_ODzvE.App\\Controller\\PlayerInvitationController::checkUser()', 'getPlayerInvitationControllercheckUserService', true],
            'App\\Controller\\PlayerInvitationController:invitePlayer' => ['privates', '.service_locator.BVux.Zu.App\\Controller\\PlayerInvitationController::invitePlayer()', 'getPlayerInvitationControllerinvitePlayerService', true],
            'App\\Controller\\PlayerInvitationController:removeUserFromJdr' => ['privates', '.service_locator.cPirmC2.App\\Controller\\PlayerInvitationController::removeUserFromJdr()', 'getPlayerInvitationControllerremoveUserFromJdrService', true],
            'App\\Controller\\ProfileController:edit' => ['privates', '.service_locator.gigYcBf.App\\Controller\\ProfileController::edit()', 'getProfileControllereditService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.QVAk1vM.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController:verifyUserEmail' => ['privates', '.service_locator.fdTWzgN.App\\Controller\\RegistrationController::verifyUserEmail()', 'getRegistrationControllerverifyUserEmailService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\GroupeJDRController::index' => '?',
            'App\\Controller\\GroupeJDRController::new' => '?',
            'App\\Controller\\GroupeJDRController::show' => '?',
            'App\\Controller\\GroupeJDRController::edit' => '?',
            'App\\Controller\\GroupeJDRController::delete' => '?',
            'App\\Controller\\InvitationController::index' => '?',
            'App\\Controller\\InvitationController::respond' => '?',
            'App\\Controller\\MyGameController::index' => '?',
            'App\\Controller\\PlayerInvitationController::checkUser' => '?',
            'App\\Controller\\PlayerInvitationController::invitePlayer' => '?',
            'App\\Controller\\PlayerInvitationController::removeUserFromJdr' => '?',
            'App\\Controller\\ProfileController::edit' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verifyUserEmail' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\GroupeJDRController:index' => '?',
            'App\\Controller\\GroupeJDRController:new' => '?',
            'App\\Controller\\GroupeJDRController:show' => '?',
            'App\\Controller\\GroupeJDRController:edit' => '?',
            'App\\Controller\\GroupeJDRController:delete' => '?',
            'App\\Controller\\InvitationController:index' => '?',
            'App\\Controller\\InvitationController:respond' => '?',
            'App\\Controller\\MyGameController:index' => '?',
            'App\\Controller\\PlayerInvitationController:checkUser' => '?',
            'App\\Controller\\PlayerInvitationController:invitePlayer' => '?',
            'App\\Controller\\PlayerInvitationController:removeUserFromJdr' => '?',
            'App\\Controller\\ProfileController:edit' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verifyUserEmail' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);
    }
}
