<?php

namespace ContainerXkoRc0e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvitationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.t03gBDU.App\Entity\Invitation' shared service.
     *
     * @return \App\Entity\Invitation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.t03gBDU": it needs an instance of "App\\Entity\\Invitation" but this type has been excluded in "config/services.yaml".');
    }
}
