<?php

namespace ContainerAp7YKoc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroupeJDRRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\GroupeJDRRepository' shared autowired service.
     *
     * @return \App\Repository\GroupeJDRRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'GroupeJDRRepository.php';

        return $container->privates['App\\Repository\\GroupeJDRRepository'] = new \App\Repository\GroupeJDRRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
