<?php

namespace ContainerVN8KaQI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMyGameControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RvFgQI_.App\Controller\MyGameController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RvFgQI_.App\\Controller\\MyGameController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'jdrRepository' => ['privates', 'App\\Repository\\GroupeJDRRepository', 'getGroupeJDRRepositoryService', true],
        ], [
            'jdrRepository' => 'App\\Repository\\GroupeJDRRepository',
        ]))->withContext('App\\Controller\\MyGameController::index()', $container);
    }
}
