<?php

namespace ContainerUFQJYLE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PPw4IaGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PPw4IaG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PPw4IaG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\ContactController::index' => ['privates', '.service_locator.dPOu_jk.App\\Controller\\ContactController::index()', 'getContactControllerindexService', true],
            'App\\Controller\\GroupeJDRController::index' => ['privates', '.service_locator.SE5FUJN.App\\Controller\\GroupeJDRController::index()', 'getGroupeJDRControllerindexService', true],
            'App\\Controller\\GroupeJDRController::new' => ['privates', '.service_locator..fUBbna.App\\Controller\\GroupeJDRController::new()', 'getGroupeJDRControllernewService', true],
            'App\\Controller\\GroupeJDRController::show' => ['privates', '.service_locator.gIBvJd7.App\\Controller\\GroupeJDRController::show()', 'getGroupeJDRControllershowService', true],
            'App\\Controller\\GroupeJDRController::edit' => ['privates', '.service_locator.CzRsto_.App\\Controller\\GroupeJDRController::edit()', 'getGroupeJDRControllereditService', true],
            'App\\Controller\\GroupeJDRController::delete' => ['privates', '.service_locator.8bi2G4e.App\\Controller\\GroupeJDRController::delete()', 'getGroupeJDRControllerdeleteService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.uqAk9vV.App\\Controller\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\InvitationController::index' => ['privates', '.service_locator.BhavcCd.App\\Controller\\InvitationController::index()', 'getInvitationControllerindexService', true],
            'App\\Controller\\InvitationController::getPendingInvitations' => ['privates', '.service_locator.P.blNFL.App\\Controller\\InvitationController::getPendingInvitations()', 'getInvitationControllergetPendingInvitationsService', true],
            'App\\Controller\\InvitationController::respondInvitation' => ['privates', '.service_locator.t03gBDU.App\\Controller\\InvitationController::respondInvitation()', 'getInvitationControllerrespondInvitationService', true],
            'App\\Controller\\MyGameController::index' => ['privates', '.service_locator.RvFgQI_.App\\Controller\\MyGameController::index()', 'getMyGameControllerindexService', true],
            'App\\Controller\\PlayerInvitationController::checkUser' => ['privates', '.service_locator.D_ODzvE.App\\Controller\\PlayerInvitationController::checkUser()', 'getPlayerInvitationControllercheckUserService', true],
            'App\\Controller\\PlayerInvitationController::removeUserFromJdr' => ['privates', '.service_locator.cPirmC2.App\\Controller\\PlayerInvitationController::removeUserFromJdr()', 'getPlayerInvitationControllerremoveUserFromJdrService', true],
            'App\\Controller\\PlayerInvitationController::requestJoin' => ['privates', '.service_locator.bjAJnBR.App\\Controller\\PlayerInvitationController::requestJoin()', 'getPlayerInvitationControllerrequestJoinService', true],
            'App\\Controller\\PlayerInvitationController::respondInvitation' => ['privates', '.service_locator.P.blNFL.App\\Controller\\PlayerInvitationController::respondInvitation()', 'getPlayerInvitationControllerrespondInvitationService', true],
            'App\\Controller\\ProfileController::edit' => ['privates', '.service_locator.gigYcBf.App\\Controller\\ProfileController::edit()', 'getProfileControllereditService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.QVAk1vM.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController::verifyUserEmail' => ['privates', '.service_locator.SSsS_et.App\\Controller\\RegistrationController::verifyUserEmail()', 'getRegistrationControllerverifyUserEmailService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\ContactController:index' => ['privates', '.service_locator.dPOu_jk.App\\Controller\\ContactController::index()', 'getContactControllerindexService', true],
            'App\\Controller\\GroupeJDRController:index' => ['privates', '.service_locator.SE5FUJN.App\\Controller\\GroupeJDRController::index()', 'getGroupeJDRControllerindexService', true],
            'App\\Controller\\GroupeJDRController:new' => ['privates', '.service_locator..fUBbna.App\\Controller\\GroupeJDRController::new()', 'getGroupeJDRControllernewService', true],
            'App\\Controller\\GroupeJDRController:show' => ['privates', '.service_locator.gIBvJd7.App\\Controller\\GroupeJDRController::show()', 'getGroupeJDRControllershowService', true],
            'App\\Controller\\GroupeJDRController:edit' => ['privates', '.service_locator.CzRsto_.App\\Controller\\GroupeJDRController::edit()', 'getGroupeJDRControllereditService', true],
            'App\\Controller\\GroupeJDRController:delete' => ['privates', '.service_locator.8bi2G4e.App\\Controller\\GroupeJDRController::delete()', 'getGroupeJDRControllerdeleteService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.uqAk9vV.App\\Controller\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\InvitationController:index' => ['privates', '.service_locator.BhavcCd.App\\Controller\\InvitationController::index()', 'getInvitationControllerindexService', true],
            'App\\Controller\\InvitationController:getPendingInvitations' => ['privates', '.service_locator.P.blNFL.App\\Controller\\InvitationController::getPendingInvitations()', 'getInvitationControllergetPendingInvitationsService', true],
            'App\\Controller\\InvitationController:respondInvitation' => ['privates', '.service_locator.t03gBDU.App\\Controller\\InvitationController::respondInvitation()', 'getInvitationControllerrespondInvitationService', true],
            'App\\Controller\\MyGameController:index' => ['privates', '.service_locator.RvFgQI_.App\\Controller\\MyGameController::index()', 'getMyGameControllerindexService', true],
            'App\\Controller\\PlayerInvitationController:checkUser' => ['privates', '.service_locator.D_ODzvE.App\\Controller\\PlayerInvitationController::checkUser()', 'getPlayerInvitationControllercheckUserService', true],
            'App\\Controller\\PlayerInvitationController:removeUserFromJdr' => ['privates', '.service_locator.cPirmC2.App\\Controller\\PlayerInvitationController::removeUserFromJdr()', 'getPlayerInvitationControllerremoveUserFromJdrService', true],
            'App\\Controller\\PlayerInvitationController:requestJoin' => ['privates', '.service_locator.bjAJnBR.App\\Controller\\PlayerInvitationController::requestJoin()', 'getPlayerInvitationControllerrequestJoinService', true],
            'App\\Controller\\PlayerInvitationController:respondInvitation' => ['privates', '.service_locator.P.blNFL.App\\Controller\\PlayerInvitationController::respondInvitation()', 'getPlayerInvitationControllerrespondInvitationService', true],
            'App\\Controller\\ProfileController:edit' => ['privates', '.service_locator.gigYcBf.App\\Controller\\ProfileController::edit()', 'getProfileControllereditService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.QVAk1vM.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController:verifyUserEmail' => ['privates', '.service_locator.SSsS_et.App\\Controller\\RegistrationController::verifyUserEmail()', 'getRegistrationControllerverifyUserEmailService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ContactController::index' => '?',
            'App\\Controller\\GroupeJDRController::index' => '?',
            'App\\Controller\\GroupeJDRController::new' => '?',
            'App\\Controller\\GroupeJDRController::show' => '?',
            'App\\Controller\\GroupeJDRController::edit' => '?',
            'App\\Controller\\GroupeJDRController::delete' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\InvitationController::index' => '?',
            'App\\Controller\\InvitationController::getPendingInvitations' => '?',
            'App\\Controller\\InvitationController::respondInvitation' => '?',
            'App\\Controller\\MyGameController::index' => '?',
            'App\\Controller\\PlayerInvitationController::checkUser' => '?',
            'App\\Controller\\PlayerInvitationController::removeUserFromJdr' => '?',
            'App\\Controller\\PlayerInvitationController::requestJoin' => '?',
            'App\\Controller\\PlayerInvitationController::respondInvitation' => '?',
            'App\\Controller\\ProfileController::edit' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verifyUserEmail' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ContactController:index' => '?',
            'App\\Controller\\GroupeJDRController:index' => '?',
            'App\\Controller\\GroupeJDRController:new' => '?',
            'App\\Controller\\GroupeJDRController:show' => '?',
            'App\\Controller\\GroupeJDRController:edit' => '?',
            'App\\Controller\\GroupeJDRController:delete' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\InvitationController:index' => '?',
            'App\\Controller\\InvitationController:getPendingInvitations' => '?',
            'App\\Controller\\InvitationController:respondInvitation' => '?',
            'App\\Controller\\MyGameController:index' => '?',
            'App\\Controller\\PlayerInvitationController:checkUser' => '?',
            'App\\Controller\\PlayerInvitationController:removeUserFromJdr' => '?',
            'App\\Controller\\PlayerInvitationController:requestJoin' => '?',
            'App\\Controller\\PlayerInvitationController:respondInvitation' => '?',
            'App\\Controller\\ProfileController:edit' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verifyUserEmail' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);
    }
}
