<?php

namespace ContainerBx6ItFe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationControllerinvitationsNotificationsIndexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.W.AipcL.App\Controller\NotificationController::invitationsNotificationsIndex()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.W.AipcL.App\\Controller\\NotificationController::invitationsNotificationsIndex()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'invitationRepository' => ['privates', 'App\\Repository\\InvitationRepository', 'getInvitationRepositoryService', false],
            'notificationRepository' => ['privates', 'App\\Repository\\NotificationRepository', 'getNotificationRepositoryService', false],
            'friendshipRepository' => ['privates', 'App\\Repository\\FriendshipRepository', 'getFriendshipRepositoryService', false],
        ], [
            'invitationRepository' => 'App\\Repository\\InvitationRepository',
            'notificationRepository' => 'App\\Repository\\NotificationRepository',
            'friendshipRepository' => 'App\\Repository\\FriendshipRepository',
        ]))->withContext('App\\Controller\\NotificationController::invitationsNotificationsIndex()', $container);
    }
}
