<?php

namespace ContainerBx6ItFe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationControllerrespondNotificationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.S5Dp5Zc.App\Controller\NotificationController::respondNotification()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.S5Dp5Zc.App\\Controller\\NotificationController::respondNotification()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'notification' => ['privates', '.errored..service_locator.S5Dp5Zc.App\\Entity\\Notification', NULL, 'Cannot autowire service ".service_locator.S5Dp5Zc": it needs an instance of "App\\Entity\\Notification" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'notification' => 'App\\Entity\\Notification',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\NotificationController::respondNotification()', $container);
    }
}
