<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class GroupeJDR extends \App\Entity\GroupeJDR implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'categories' => [parent::class, 'categories', null],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'edit_at' => [parent::class, 'edit_at', null],
        "\0".parent::class."\0".'events' => [parent::class, 'events', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'invitations' => [parent::class, 'invitations', null],
        "\0".parent::class."\0".'isArchived' => [parent::class, 'isArchived', null],
        "\0".parent::class."\0".'licence' => [parent::class, 'licence', null],
        "\0".parent::class."\0".'maxPlayer' => [parent::class, 'maxPlayer', null],
        "\0".parent::class."\0".'notificationHistories' => [parent::class, 'notificationHistories', null],
        "\0".parent::class."\0".'notifications' => [parent::class, 'notifications', null],
        "\0".parent::class."\0".'owner' => [parent::class, 'owner', null],
        "\0".parent::class."\0".'picture' => [parent::class, 'picture', null],
        "\0".parent::class."\0".'playerMemberships' => [parent::class, 'playerMemberships', null],
        "\0".parent::class."\0".'players' => [parent::class, 'players', null],
        "\0".parent::class."\0".'recrutement' => [parent::class, 'recrutement', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null],
        "\0".parent::class."\0".'users' => [parent::class, 'users', null],
        'categories' => [parent::class, 'categories', null],
        'created_at' => [parent::class, 'created_at', null],
        'description' => [parent::class, 'description', null],
        'edit_at' => [parent::class, 'edit_at', null],
        'events' => [parent::class, 'events', null],
        'id' => [parent::class, 'id', null],
        'invitations' => [parent::class, 'invitations', null],
        'isArchived' => [parent::class, 'isArchived', null],
        'licence' => [parent::class, 'licence', null],
        'maxPlayer' => [parent::class, 'maxPlayer', null],
        'notificationHistories' => [parent::class, 'notificationHistories', null],
        'notifications' => [parent::class, 'notifications', null],
        'owner' => [parent::class, 'owner', null],
        'picture' => [parent::class, 'picture', null],
        'playerMemberships' => [parent::class, 'playerMemberships', null],
        'players' => [parent::class, 'players', null],
        'recrutement' => [parent::class, 'recrutement', null],
        'status' => [parent::class, 'status', null],
        'title' => [parent::class, 'title', null],
        'users' => [parent::class, 'users', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
