<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'avatar' => [parent::class, 'avatar', null],
        "\0".parent::class."\0".'banner' => [parent::class, 'banner', null],
        "\0".parent::class."\0".'bio' => [parent::class, 'bio', null],
        "\0".parent::class."\0".'birthDate' => [parent::class, 'birthDate', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'favoriteGroupeJDR' => [parent::class, 'favoriteGroupeJDR', null],
        "\0".parent::class."\0".'firstName' => [parent::class, 'firstName', null],
        "\0".parent::class."\0".'friendships' => [parent::class, 'friendships', null],
        "\0".parent::class."\0".'groupeJDRs' => [parent::class, 'groupeJDRs', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'invitationPending' => [parent::class, 'invitationPending', null],
        "\0".parent::class."\0".'invitations' => [parent::class, 'invitations', null],
        "\0".parent::class."\0".'ipAddress' => [parent::class, 'ipAddress', null],
        "\0".parent::class."\0".'isVerified' => [parent::class, 'isVerified', null],
        "\0".parent::class."\0".'isVip' => [parent::class, 'isVip', null],
        "\0".parent::class."\0".'joinedGroupeJDRs' => [parent::class, 'joinedGroupeJDRs', null],
        "\0".parent::class."\0".'lastName' => [parent::class, 'lastName', null],
        "\0".parent::class."\0".'notificationHistories' => [parent::class, 'notificationHistories', null],
        "\0".parent::class."\0".'notifications' => [parent::class, 'notifications', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'playerMemberships' => [parent::class, 'playerMemberships', null],
        "\0".parent::class."\0".'receiverFriendships' => [parent::class, 'receiverFriendships', null],
        "\0".parent::class."\0".'relatedNotifications' => [parent::class, 'relatedNotifications', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        "\0".parent::class."\0".'stripeCustomerId' => [parent::class, 'stripeCustomerId', null],
        "\0".parent::class."\0".'username' => [parent::class, 'username', null],
        'avatar' => [parent::class, 'avatar', null],
        'banner' => [parent::class, 'banner', null],
        'bio' => [parent::class, 'bio', null],
        'birthDate' => [parent::class, 'birthDate', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'email' => [parent::class, 'email', null],
        'favoriteGroupeJDR' => [parent::class, 'favoriteGroupeJDR', null],
        'firstName' => [parent::class, 'firstName', null],
        'friendships' => [parent::class, 'friendships', null],
        'groupeJDRs' => [parent::class, 'groupeJDRs', null],
        'id' => [parent::class, 'id', null],
        'invitationPending' => [parent::class, 'invitationPending', null],
        'invitations' => [parent::class, 'invitations', null],
        'ipAddress' => [parent::class, 'ipAddress', null],
        'isVerified' => [parent::class, 'isVerified', null],
        'isVip' => [parent::class, 'isVip', null],
        'joinedGroupeJDRs' => [parent::class, 'joinedGroupeJDRs', null],
        'lastName' => [parent::class, 'lastName', null],
        'notificationHistories' => [parent::class, 'notificationHistories', null],
        'notifications' => [parent::class, 'notifications', null],
        'password' => [parent::class, 'password', null],
        'playerMemberships' => [parent::class, 'playerMemberships', null],
        'receiverFriendships' => [parent::class, 'receiverFriendships', null],
        'relatedNotifications' => [parent::class, 'relatedNotifications', null],
        'roles' => [parent::class, 'roles', null],
        'stripeCustomerId' => [parent::class, 'stripeCustomerId', null],
        'username' => [parent::class, 'username', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
