<?php

namespace ContainerD4KBtYq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlayerInvitationControllerrequestJoinService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bjAJnBR.App\Controller\PlayerInvitationController::requestJoin()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bjAJnBR.App\\Controller\\PlayerInvitationController::requestJoin()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'groupeJdrRepository' => ['privates', 'App\\Repository\\GroupeJDRRepository', 'getGroupeJDRRepositoryService', true],
            'invitationRepository' => ['privates', 'App\\Repository\\InvitationRepository', 'getInvitationRepositoryService', true],
        ], [
            'entityManager' => '?',
            'groupeJdrRepository' => 'App\\Repository\\GroupeJDRRepository',
            'invitationRepository' => 'App\\Repository\\InvitationRepository',
        ]))->withContext('App\\Controller\\PlayerInvitationController::requestJoin()', $container);
    }
}
