<?php

namespace Container9qRQZvE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileControllereditAvatarService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9wFACBr.App\Controller\ProfileController::editAvatar()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.9wFACBr'] ?? $container->load('get_ServiceLocator_9wFACBrService'));

        if (isset($container->privates['.service_locator.9wFACBr.App\\Controller\\ProfileController::editAvatar()'])) {
            return $container->privates['.service_locator.9wFACBr.App\\Controller\\ProfileController::editAvatar()'];
        }

        return $container->privates['.service_locator.9wFACBr.App\\Controller\\ProfileController::editAvatar()'] = $a->withContext('App\\Controller\\ProfileController::editAvatar()', $container);
    }
}
