<?php

namespace ContainerWNvH8nf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Iqb2BYLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Iqb2BYL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Iqb2BYL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'fileUploaderService' => ['privates', 'App\\Service\\FileUploaderService', 'getFileUploaderServiceService', true],
        ], [
            'slugger' => '?',
            'entityManager' => '?',
            'fileUploaderService' => 'App\\Service\\FileUploaderService',
        ]);
    }
}
