<?php

namespace ContainerWNvH8nf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileUploaderServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\FileUploaderService' shared autowired service.
     *
     * @return \App\Service\FileUploaderService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'FileUploaderService.php';

        return $container->privates['App\\Service\\FileUploaderService'] = new \App\Service\FileUploaderService();
    }
}
