<?php

namespace ContainerWNvH8nf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroupeJDR2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.dLPkU1o.App\Entity\GroupeJDR' shared service.
     *
     * @return \App\Entity\GroupeJDR
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.dLPkU1o": it needs an instance of "App\\Entity\\GroupeJDR" but this type has been excluded in "config/services.yaml".');
    }
}
