<?php

namespace ContainerWytuLt4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\EventRepository' shared autowired service.
     *
     * @return \App\Repository\EventRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/EventRepository.php';

        return $container->privates['App\\Repository\\EventRepository'] = new \App\Repository\EventRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
