<?php

namespace ContainerWytuLt4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_Extension_TogglePasswordService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'form.extension.toggle_password' shared service.
     *
     * @return \Symfony\UX\TogglePassword\Form\TogglePasswordTypeExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractTypeExtension.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-toggle-password/src/Form/TogglePasswordTypeExtension.php';

        return $container->privates['form.extension.toggle_password'] = new \Symfony\UX\TogglePassword\Form\TogglePasswordTypeExtension(($container->services['translator'] ?? self::getTranslatorService($container)));
    }
}
