<?php

namespace ContainerWytuLt4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFavorisControlleraddFavoriteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8bi2G4e.App\Controller\FavorisController::addFavorite()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.8bi2G4e'] ?? $container->load('get_ServiceLocator_8bi2G4eService'));

        if (isset($container->privates['.service_locator.8bi2G4e.App\\Controller\\FavorisController::addFavorite()'])) {
            return $container->privates['.service_locator.8bi2G4e.App\\Controller\\FavorisController::addFavorite()'];
        }

        return $container->privates['.service_locator.8bi2G4e.App\\Controller\\FavorisController::addFavorite()'] = $a->withContext('App\\Controller\\FavorisController::addFavorite()', $container);
    }
}
