<?php

namespace ContainerWytuLt4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroupeJDRControllerleaveService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.f8sH7ah.App\Controller\GroupeJDRController::leave()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.f8sH7ah.App\\Controller\\GroupeJDRController::leave()'] = ($container->privates['.service_locator.f8sH7ah'] ?? $container->load('get_ServiceLocator_F8sH7ahService'))->withContext('App\\Controller\\GroupeJDRController::leave()', $container);
    }
}
