<?php

namespace ContainerWytuLt4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPasswordChangeSettingsTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\PasswordChangeSettingsType' shared autowired service.
     *
     * @return \App\Form\PasswordChangeSettingsType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/PasswordChangeSettingsType.php';

        return $container->privates['App\\Form\\PasswordChangeSettingsType'] = new \App\Form\PasswordChangeSettingsType();
    }
}
