<?php

namespace Container58wFiBK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlayerInvitationControllerrespondInvitationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gsAwGE9.App\Controller\PlayerInvitationController::respondInvitation()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gsAwGE9.App\\Controller\\PlayerInvitationController::respondInvitation()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'playerMembershipRepository' => ['privates', 'App\\Repository\\PlayerMembershipRepository', 'getPlayerMembershipRepositoryService', true],
        ], [
            'entityManager' => '?',
            'playerMembershipRepository' => 'App\\Repository\\PlayerMembershipRepository',
        ]))->withContext('App\\Controller\\PlayerInvitationController::respondInvitation()', $container);
    }
}
