<?php

namespace Container2J1vZ0x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SE5FUJNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SE5FUJN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SE5FUJN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'groupeJDRRepository' => ['privates', 'App\\Repository\\GroupeJDRRepository', 'getGroupeJDRRepositoryService', true],
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
        ], [
            'groupeJDRRepository' => 'App\\Repository\\GroupeJDRRepository',
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
        ]);
    }
}
