<?php

namespace Container2J1vZ0x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroupeJDRControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gIBvJd7.App\Controller\GroupeJDRController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gIBvJd7.App\\Controller\\GroupeJDRController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'groupeJDR' => ['privates', '.errored..service_locator.gIBvJd7.App\\Entity\\GroupeJDR', NULL, 'Cannot autowire service ".service_locator.gIBvJd7": it needs an instance of "App\\Entity\\GroupeJDR" but this type has been excluded in "config/services.yaml".'],
            'groupeJDRRepository' => ['privates', 'App\\Repository\\GroupeJDRRepository', 'getGroupeJDRRepositoryService', true],
            'invitationRepository' => ['privates', 'App\\Repository\\InvitationRepository', 'getInvitationRepositoryService', false],
        ], [
            'groupeJDR' => 'App\\Entity\\GroupeJDR',
            'groupeJDRRepository' => 'App\\Repository\\GroupeJDRRepository',
            'invitationRepository' => 'App\\Repository\\InvitationRepository',
        ]))->withContext('App\\Controller\\GroupeJDRController::show()', $container);
    }
}
