<?php

namespace Container2J1vZ0x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IxU2ZKg.App\Controller\ProfileController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IxU2ZKg.App\\Controller\\ProfileController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'friendshipRepository' => ['privates', 'App\\Repository\\FriendshipRepository', 'getFriendshipRepositoryService', false],
        ], [
            'entityManager' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
            'friendshipRepository' => 'App\\Repository\\FriendshipRepository',
        ]))->withContext('App\\Controller\\ProfileController::show()', $container);
    }
}
