<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMlsixTT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMlsixTT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMlsixTT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMlsixTT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMlsixTT\App_KernelDevDebugContainer([
    'container.build_hash' => 'MlsixTT',
    'container.build_id' => '5819fd35',
    'container.build_time' => 1726312770,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMlsixTT');
