<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2J1vZ0x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2J1vZ0x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2J1vZ0x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2J1vZ0x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2J1vZ0x\App_KernelDevDebugContainer([
    'container.build_hash' => '2J1vZ0x',
    'container.build_id' => '84ae293f',
    'container.build_time' => 1729786036,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container2J1vZ0x');
