<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9qRQZvE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9qRQZvE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9qRQZvE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9qRQZvE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9qRQZvE\App_KernelDevDebugContainer([
    'container.build_hash' => '9qRQZvE',
    'container.build_id' => 'f64c185a',
    'container.build_time' => 1729531117,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container9qRQZvE');
