<?php

namespace Container2taVVo8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlayerInvitationControllerinvitePlayerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BVux.Zu.App\Controller\PlayerInvitationController::invitePlayer()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BVux.Zu.App\\Controller\\PlayerInvitationController::invitePlayer()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'groupeJDRRepository' => ['privates', 'App\\Repository\\GroupeJDRRepository', 'getGroupeJDRRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'userRepository' => 'App\\Repository\\UserRepository',
            'groupeJDRRepository' => 'App\\Repository\\GroupeJDRRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\PlayerInvitationController::invitePlayer()', $container);
    }
}
